[versions]
    # Base:
activityCompose = "1.9.0"
agp = "8.4.1"
composeBom = "2023.08.00"
coreKtx = "1.13.1"
kotlin = "1.9.0"
lifecycleRuntimeKtx = "2.8.2"
androidSdk-compile = "34"
androidSdk-min = "24"
androidSdk-target = "33"

    # Detekt
detekt = "1.23.3"

[libraries]
    # Base:
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

    # Detekt:
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }

[plugins]
    # Base:
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

    # Detekt:
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt"}
android-library = { id = "com.android.library", version.ref = "agp" }
